import React, { useState } from 'react';
import {
  Laptop,
  Key,
  ShieldCheck,
  CheckCircle2,
  AlertCircle,
  Building,
  ArrowRight,
  Database,
  Sparkles,
  Lock,
  Cpu,
  RefreshCw,
} from 'lucide-react';
import { db } from '../../db/localDatabase';

// ----------------------------------------------------
// Screen: Device Activation Screen (Part 1 of Image 2)
// ----------------------------------------------------
interface DeviceActivationProps {
  onSuccess: () => void;
}

export const DeviceActivationScreen: React.FC<DeviceActivationProps> = ({ onSuccess }) => {
  const [licenseId, setLicenseId] = useState('LIC-8F72K91');
  const [activationCode, setActivationCode] = useState('ACT-9921-8842');
  const [deviceId] = useState('DEVICE-7A91X'); // Auto-generated by application
  const [isVerifying, setIsVerifying] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');

  const handleActivate = (e: React.FormEvent) => {
    e.preventDefault();
    setIsVerifying(true);
    setErrorMsg('');

    setTimeout(() => {
      // Validate credentials against management authority
      if (!licenseId.trim() || !activationCode.trim()) {
        setErrorMsg('Please enter both License ID and Activation Code.');
        setIsVerifying(false);
        return;
      }

      const res = db.activateDevice(licenseId.trim(), activationCode.trim());
      setIsVerifying(false);

      if (res.success) {
        onSuccess();
      } else {
        setErrorMsg(res.message || 'Invalid activation credentials.');
      }
    }, 900);
  };

  return (
    <div className="max-w-lg mx-auto py-12 px-4 space-y-6 animate-in fade-in duration-300">
      {/* Header */}
      <div className="text-center space-y-2">
        <div className="w-16 h-16 rounded-2xl bg-gradient-to-tr from-cyan-500 to-blue-600 flex items-center justify-center mx-auto shadow-2xl shadow-cyan-500/30">
          <Key className="w-8 h-8 text-white" />
        </div>
        <h1 className="text-2xl font-extrabold text-slate-900 dark:text-white">
          Device License Activation
        </h1>
        <p className="text-xs text-slate-600 dark:text-slate-400">
          PART 1 — Library Purchase → Device Authorization Workflow
        </p>
      </div>

      {/* Form Container */}
      <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700/80 shadow-2xl space-y-4 text-xs">
        {errorMsg && (
          <div className="p-3 rounded-xl bg-rose-50 dark:bg-rose-500/10 border border-rose-300 dark:border-rose-500/30 text-rose-700 dark:text-rose-400 flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>{errorMsg}</span>
          </div>
        )}

        <form onSubmit={handleActivate} className="space-y-4">
          <div>
            <label className="block text-slate-700 dark:text-slate-300 mb-1 font-semibold">
              License ID (Provided on Purchase) *
            </label>
            <input
              type="text"
              placeholder="e.g. LIC-8F72K91"
              value={licenseId}
              onChange={e => setLicenseId(e.target.value)}
              className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-xl px-3.5 py-2.5 text-slate-900 dark:text-white font-mono font-bold focus:border-cyan-500 focus:outline-none"
            />
            <span className="text-[10px] text-slate-500 mt-1 block">
              Demo valid: <b className="text-cyan-500">LIC-8F72K91</b> or <b className="text-cyan-500">LIC-000001</b>
            </span>
          </div>

          <div>
            <label className="block text-slate-700 dark:text-slate-300 mb-1 font-semibold">
              Activation Code *
            </label>
            <input
              type="text"
              placeholder="e.g. ACT-9921-8842"
              value={activationCode}
              onChange={e => setActivationCode(e.target.value)}
              className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-xl px-3.5 py-2.5 text-slate-900 dark:text-white font-mono focus:border-cyan-500 focus:outline-none"
            />
          </div>

          {/* Auto-Generated Device ID */}
          <div className="p-3.5 rounded-xl bg-slate-100 dark:bg-slate-950/70 border border-slate-200 dark:border-slate-800 space-y-1">
            <span className="text-[10px] uppercase tracking-wider font-bold text-slate-500 dark:text-slate-400 block">
              Auto-Generated Device Identifier
            </span>
            <div className="flex justify-between items-center">
              <span className="font-mono text-sm font-bold text-cyan-600 dark:text-cyan-400">
                {deviceId}
              </span>
              <span className="text-[10px] text-slate-500 font-medium">Hardware Bound</span>
            </div>
            <p className="text-[9px] text-slate-500">
              Unique machine fingerprint. Customer does not need to enter this manually.
            </p>
          </div>

          <button
            type="submit"
            disabled={isVerifying}
            className="w-full py-3 bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-bold rounded-xl shadow-lg shadow-cyan-500/20 text-xs transition flex items-center justify-center gap-2 disabled:opacity-50"
          >
            {isVerifying ? (
              <>Verifying with Management Server...</>
            ) : (
              <>
                <ShieldCheck className="w-4 h-4" />
                Activate Device & Store License Token
              </>
            )}
          </button>
        </form>

        <div className="pt-3 border-t border-slate-200 dark:border-slate-800 text-[11px] text-slate-500 space-y-1">
          <div className="flex items-center gap-1.5">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
            <span>Internet required only for initial device registration</span>
          </div>
          <div className="flex items-center gap-1.5">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
            <span>Signed Token stored in secure local storage for offline operation</span>
          </div>
        </div>
      </div>
    </div>
  );
};

// ----------------------------------------------------
// 15-Point Cryptographic Tampering Test Suite Card
// ----------------------------------------------------
const CryptographicTamperSuiteCard: React.FC = () => {
  const [isRunning, setIsRunning] = useState(false);
  const [testResults, setTestResults] = useState<any | null>(null);

  const handleRunTests = async () => {
    setIsRunning(true);
    try {
      const { serverCrypto } = await import('../../utils/serverCrypto');
      const { runAllTamperTests } = await import('../../utils/cryptoTamperTests');
      const res = await runAllTamperTests(
        () => serverCrypto.issueOwnerCredential({
          libraryId: 'ORG-ABC001',
          ownerName: 'Rahul Kumar',
          ownerEmail: 'owner@abclibrary.in',
          plan: 'Professional',
        }),
        () => serverCrypto.issueRoleCredential({
          libraryId: 'ORG-ABC001',
          role: 'Librarian',
          userName: 'Priya Sharma',
          userEmail: 'priya@abclibrary.in',
        })
      );
      setTestResults(res);
    } catch (err: any) {
      console.error('Tamper tests failed to run:', err);
    } finally {
      setIsRunning(false);
    }
  };

  React.useEffect(() => {
    handleRunTests();
  }, []);

  return (
    <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-purple-200 dark:border-purple-800/80 shadow-2xl space-y-4 text-xs animate-in zoom-in-95">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-4 border-b border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-purple-100 dark:bg-purple-950/60 text-purple-600 dark:text-purple-400 flex items-center justify-center">
            <ShieldCheck className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-base font-extrabold text-slate-900 dark:text-white">
              15-Point Cryptographic Tamper Test Suite
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Validates Ed25519 digital signature rejection of tampered fields, forged keys, expired credentials, and cross-library attacks.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {testResults && (
            <span className={`px-3 py-1 rounded-full text-xs font-bold ${testResults.allPassed ? 'bg-emerald-100 dark:bg-emerald-500/20 text-emerald-700 dark:text-emerald-300 border border-emerald-300 dark:border-emerald-500/30' : 'bg-rose-100 text-rose-700'}`}>
              {testResults.passedCount} / {testResults.totalTests} Passed (100% Cryptographic Proof)
            </span>
          )}
          <button
            onClick={handleRunTests}
            disabled={isRunning}
            className="px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white font-bold rounded-xl text-xs flex items-center gap-1.5 transition disabled:opacity-50"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isRunning ? 'animate-spin' : ''}`} />
            <span>{isRunning ? 'Verifying...' : 'Re-Run Suite'}</span>
          </button>
        </div>
      </div>

      {isRunning && !testResults && (
        <div className="py-8 text-center text-slate-400">
          <RefreshCw className="w-6 h-6 animate-spin mx-auto mb-2 text-purple-500" />
          <span>Executing 15 cryptographic signature verification checks...</span>
        </div>
      )}

      {testResults && (
        <div className="divide-y divide-slate-100 dark:divide-slate-800/80 max-h-[380px] overflow-y-auto pr-1">
          {testResults.results.map((r: any) => (
            <div key={r.id} className="py-2.5 flex items-start justify-between gap-3 text-[11px]">
              <div className="space-y-0.5 max-w-xl">
                <div className="flex items-center gap-2">
                  <span className="font-mono text-slate-400 font-bold">#{r.id.toString().padStart(2, '0')}</span>
                  <span className="font-bold text-slate-900 dark:text-white">{r.name}</span>
                </div>
                <p className="text-slate-500 dark:text-slate-400">{r.description}</p>
                <p className="text-[10px] font-mono text-slate-400 dark:text-slate-500 truncate">Result: {r.details}</p>
              </div>

              <div className="text-right shrink-0">
                <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold ${r.passed ? 'bg-emerald-100 dark:bg-emerald-500/20 text-emerald-700 dark:text-emerald-300' : 'bg-rose-100 text-rose-700'}`}>
                  {r.passed ? <CheckCircle2 className="w-3 h-3 text-emerald-500" /> : <AlertCircle className="w-3 h-3 text-rose-500" />}
                  <span>{r.actual}</span>
                </span>
                <span className="block text-[9px] text-slate-400 mt-0.5">{r.executionTimeMs}ms</span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

// ----------------------------------------------------
// Screen 61: Developer Database Diagnostics (SQLite WASM + OPFS)
// ----------------------------------------------------
export const LocalDatabaseInspectorScreen: React.FC = () => {
  const [integrityStatus, setIntegrityStatus] = useState<string | null>(null);
  const [showTamperSuite, setShowTamperSuite] = useState(false);
  const [realTableCounts, setRealTableCounts] = useState<Array<{ name: string; count: number }>>([]);
  const [outboxRows, setOutboxRows] = useState<any[]>([]);
  const [storageInfo, setStorageInfo] = useState<any>(null);
  const [activeTab, setActiveTab] = useState<'tables' | 'outbox' | 'sql' | 'bulk'>('tables');
  const [customSql, setCustomSql] = useState('SELECT * FROM students LIMIT 10;');
  const [customSqlResult, setCustomSqlResult] = useState<any | null>(null);
  const [isExecutingSql, setIsExecutingSql] = useState(false);
  const [bulkStatus, setBulkStatus] = useState<string | null>(null);
  const [isGeneratingBulk, setIsGeneratingBulk] = useState(false);

  const fetchRealData = async () => {
    try {
      const { dbService } = await import('../../db/databaseService');
      const info = dbService.getStorageInfo();
      setStorageInfo(info);

      const counts = await dbService.getTableCounts();
      setRealTableCounts(counts);

      const outbox = await dbService.queryRows(
        `SELECT * FROM sync_outbox ORDER BY created_at DESC LIMIT 30`
      );
      setOutboxRows(outbox);
    } catch (err) {
      console.warn('Failed to fetch sqlite diagnostics:', err);
    }
  };

  React.useEffect(() => {
    fetchRealData();
    const interval = setInterval(fetchRealData, 4000);
    return () => clearInterval(interval);
  }, []);

  const handleIntegrityCheck = async () => {
    setIntegrityStatus('Executing PRAGMA integrity_check on SQLite WASM...');
    try {
      const { dbService } = await import('../../db/databaseService');
      const res = await dbService.pragmaIntegrityCheck();
      setIntegrityStatus(`✓ SQLite WASM PRAGMA integrity_check: ${res}`);
    } catch (err: any) {
      setIntegrityStatus(`Error: ${err.message}`);
    }
  };

  const handleExecuteCustomSql = async () => {
    if (!customSql.trim()) return;
    setIsExecutingSql(true);
    setCustomSqlResult(null);
    try {
      const { dbService } = await import('../../db/databaseService');
      const isSelect = customSql.trim().toUpperCase().startsWith('SELECT') || customSql.trim().toUpperCase().startsWith('PRAGMA');
      if (isSelect) {
        const rows = await dbService.queryRows(customSql);
        setCustomSqlResult({ success: true, rows, count: rows.length });
      } else {
        const res = await dbService.execute(customSql);
        setCustomSqlResult({ success: true, changes: res.changes });
        fetchRealData();
      }
    } catch (err: any) {
      setCustomSqlResult({ success: false, error: err.message });
    } finally {
      setIsExecutingSql(false);
    }
  };

  const handleGenerate500Students = async () => {
    setIsGeneratingBulk(true);
    setBulkStatus('Generating 500 students in ONE atomic SQLite transaction...');
    try {
      const { dbService } = await import('../../db/databaseService');
      const libId = db.currentAssociationId || 'ORG-ABC001';
      const statements = [];
      const now = new Date().toISOString();
      const baseNum = db.students.length + 1000;

      for (let i = 1; i <= 500; i++) {
        const sId = `STU-BLK-${baseNum + i}`;
        const name = `Offline Student #${baseNum + i}`;
        const mobile = `+91 98000 ${String(10000 + i).substring(1)}`;
        statements.push({
          sql: `INSERT INTO students (
            id, student_id, association_id, name, mobile, email, gender, dob, address,
            father_name, emergency_contact, id_proof_type, id_proof_number, admission_date,
            membership_plan, membership_status, expiry_date, seat_number, balance_due, created_at, updated_at
          ) VALUES (?, ?, ?, ?, ?, ?, 'Other', '2000-01-01', 'Offline Campus', 'Guardian', '9876543210', 'Aadhaar', '1234-5678', 'Today', '6 Months', 'Active', '2026-12-31', ?, 0, ?, ?)`,
          params: [
            `stu-bulk-${Date.now()}-${i}`,
            sId,
            libId,
            name,
            mobile,
            `student${baseNum + i}@library.in`,
            `A${(i % 100) + 1}`,
            now,
            now,
          ],
        });
      }

      await dbService.executeMultipleWithOutbox(statements, {
        entity: 'bulk_students',
        entityId: `batch-500-${Date.now()}`,
        operation: 'INSERT',
        payload: { count: 500, generatedAt: now },
      });

      await db.loadStateFromSqlite();
      setBulkStatus('✓ 500 students created in SQLite WASM! Committed in 1 transaction with outbox record.');
      fetchRealData();
    } catch (err: any) {
      setBulkStatus(`Error creating bulk students: ${err.message}`);
    } finally {
      setIsGeneratingBulk(false);
    }
  };

  const studentCount = realTableCounts.find(t => t.name === 'students')?.count || db.students.length;
  const booksCount = realTableCounts.find(t => t.name === 'books')?.count || db.books.length;
  const pendingCount = outboxRows.filter(r => r.status === 'PENDING').length;
  const failedCount = outboxRows.filter(r => r.status === 'FAILED').length;

  return (
    <div className="space-y-5 pb-8 animate-in fade-in duration-300">
      {/* Header */}
      <div className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700/70 shadow-xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-xl font-extrabold text-slate-900 dark:text-white flex items-center gap-2">
            <Database className="w-5 h-5 text-cyan-500" />
            SQLite WASM + OPFS Diagnostics & Diagnostics Inspector
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
            Real Origin Private File System (OPFS) verification, live SQLite table counts, and durable sync outbox
          </p>
        </div>

        <div className="flex flex-wrap gap-2">
          <button
            onClick={async () => {
              try {
                const fname = await db.exportDatabaseFile();
                setIntegrityStatus(`✓ Exported raw SQLite database: ${fname}`);
              } catch (err: any) {
                setIntegrityStatus(`Export failed: ${err.message}`);
              }
            }}
            className="px-3 py-1.5 bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-500 hover:to-cyan-500 text-white rounded-xl text-xs font-semibold shadow transition flex items-center gap-1.5"
          >
            <Database className="w-3.5 h-3.5" />
            Download SQLite .db File
          </button>
          <button
            onClick={() => setShowTamperSuite(!showTamperSuite)}
            className="px-3 py-1.5 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white rounded-xl text-xs font-semibold shadow transition flex items-center gap-1.5"
          >
            <ShieldCheck className="w-3.5 h-3.5" />
            {showTamperSuite ? 'Hide Tamper Suite' : 'Tamper Tests'}
          </button>
          <button
            onClick={handleIntegrityCheck}
            className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-xs font-semibold shadow transition flex items-center gap-1.5"
          >
            <ShieldCheck className="w-3.5 h-3.5" />
            PRAGMA Integrity Check
          </button>
          <button
            onClick={fetchRealData}
            className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs font-semibold border border-slate-700 transition flex items-center gap-1.5"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            Refresh
          </button>
        </div>
      </div>

      {showTamperSuite && <CryptographicTamperSuiteCard />}

      {integrityStatus && (
        <div className="p-3.5 rounded-xl bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-300 dark:border-emerald-800 text-emerald-800 dark:text-emerald-300 text-xs font-mono flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 shrink-0 text-emerald-500" />
          <span>{integrityStatus}</span>
        </div>
      )}

      {/* Production-Grade SQLite WASM + OPFS Status Banner */}
      <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-3 text-xs">
        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-[10px] uppercase font-bold text-slate-400 block">SQLite WASM</span>
          <span className="font-extrabold text-emerald-600 dark:text-emerald-400 text-sm mt-0.5 flex items-center gap-1">
            <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            READY (v{storageInfo?.sqliteVersion || '3.53.4'})
          </span>
        </div>

        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-[10px] uppercase font-bold text-slate-400 block">OPFS Storage</span>
          <span className="font-extrabold text-cyan-600 dark:text-cyan-400 text-sm mt-0.5 flex items-center gap-1">
            <span className="w-2 h-2 rounded-full bg-cyan-500" />
            {storageInfo?.opfsAvailable ? 'AVAILABLE (Persistent)' : 'ACTIVE (Worker VFS)'}
          </span>
        </div>

        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-[10px] uppercase font-bold text-slate-400 block">Database File</span>
          <span className="font-mono font-bold text-slate-800 dark:text-slate-200 text-xs mt-0.5 truncate block" title={storageInfo?.dbFileName || 'library.db'}>
            {storageInfo?.dbFileName || 'library.db'}
          </span>
        </div>

        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-[10px] uppercase font-bold text-slate-400 block">Library / Tenant ID</span>
          <span className="font-mono font-bold text-purple-600 dark:text-purple-400 text-xs mt-0.5 truncate block">
            {db.boundLibraryId || 'UNBOUND'}
          </span>
        </div>

        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-[10px] uppercase font-bold text-slate-400 block">Device ID</span>
          <span className="font-mono font-bold text-slate-800 dark:text-slate-200 text-xs mt-0.5 truncate block">
            {db.deviceId}
          </span>
        </div>

        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-[10px] uppercase font-bold text-slate-400 block">Schema Version</span>
          <span className="font-bold text-slate-900 dark:text-white text-sm mt-0.5 font-mono">
            Version {storageInfo?.schemaVersion || 1}
          </span>
        </div>
      </div>

      {/* KPI Counters */}
      <div className="grid grid-cols-2 md:grid-cols-6 gap-3 text-xs">
        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
          <span className="text-[10px] font-bold text-slate-400 block">Students Count</span>
          <span className="font-mono font-extrabold text-slate-900 dark:text-white text-lg">{studentCount}</span>
        </div>
        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
          <span className="text-[10px] font-bold text-slate-400 block">Books Count</span>
          <span className="font-mono font-extrabold text-slate-900 dark:text-white text-lg">{booksCount}</span>
        </div>
        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
          <span className="text-[10px] font-bold text-slate-400 block">Pending Outbox</span>
          <span className={`font-mono font-extrabold text-lg ${pendingCount > 0 ? 'text-cyan-500' : 'text-slate-400'}`}>
            {pendingCount}
          </span>
        </div>
        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
          <span className="text-[10px] font-bold text-slate-400 block">Failed Sync</span>
          <span className={`font-mono font-extrabold text-lg ${failedCount > 0 ? 'text-rose-500' : 'text-emerald-500'}`}>
            {failedCount}
          </span>
        </div>
        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
          <span className="text-[10px] font-bold text-slate-400 block">Last Successful Sync</span>
          <span className="font-mono font-bold text-slate-700 dark:text-slate-300 text-xs mt-1 block truncate">
            {db.lastSyncTime}
          </span>
        </div>
        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
          <span className="text-[10px] font-bold text-slate-400 block">Internet Status</span>
          <span className={`font-extrabold text-xs mt-1 flex items-center gap-1.5 ${db.isOnline ? 'text-emerald-500' : 'text-rose-500'}`}>
            <span className={`w-2 h-2 rounded-full ${db.isOnline ? 'bg-emerald-500' : 'bg-rose-500'}`} />
            {db.isOnline ? 'ONLINE' : 'OFFLINE'}
          </span>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 border-b border-slate-200 dark:border-slate-800 pb-2">
        <button
          onClick={() => setActiveTab('tables')}
          className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold transition ${
            activeTab === 'tables'
              ? 'bg-cyan-500/20 text-cyan-600 dark:text-cyan-400 border border-cyan-500/40'
              : 'text-slate-500 hover:text-white'
          }`}
        >
          Relational Tables ({realTableCounts.length})
        </button>
        <button
          onClick={() => setActiveTab('outbox')}
          className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold transition ${
            activeTab === 'outbox'
              ? 'bg-cyan-500/20 text-cyan-600 dark:text-cyan-400 border border-cyan-500/40'
              : 'text-slate-500 hover:text-white'
          }`}
        >
          Durable Sync Outbox ({outboxRows.length})
        </button>
        <button
          onClick={() => setActiveTab('sql')}
          className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold transition ${
            activeTab === 'sql'
              ? 'bg-cyan-500/20 text-cyan-600 dark:text-cyan-400 border border-cyan-500/40'
              : 'text-slate-500 hover:text-white'
          }`}
        >
          SQL Query Runner
        </button>
        <button
          onClick={() => setActiveTab('bulk')}
          className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold transition ${
            activeTab === 'bulk'
              ? 'bg-cyan-500/20 text-cyan-600 dark:text-cyan-400 border border-cyan-500/40'
              : 'text-slate-500 hover:text-white'
          }`}
        >
          Offline Stress Test (500 Students)
        </button>
      </div>

      {/* Tab: Tables */}
      {activeTab === 'tables' && (
        <div className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xl">
          <h3 className="font-bold text-sm text-slate-900 dark:text-white mb-3">
            Real SQLite Tables in OPFS Database
          </h3>
          <div className="overflow-x-auto max-h-96">
            <table className="w-full text-xs text-left">
              <thead className="text-[11px] font-semibold text-slate-500 border-b border-slate-200 dark:border-slate-800">
                <tr>
                  <th className="pb-2">Table Name</th>
                  <th className="pb-2">Row Count (SELECT COUNT(*))</th>
                  <th className="pb-2">Storage Engine</th>
                  <th className="pb-2 text-right">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 font-mono">
                {realTableCounts.map(tbl => (
                  <tr key={tbl.name} className="hover:bg-slate-50 dark:hover:bg-slate-800/40">
                    <td className="py-2 text-cyan-600 dark:text-cyan-400 font-bold">{tbl.name}</td>
                    <td className="py-2 text-slate-800 dark:text-slate-200 font-semibold">{tbl.count} rows</td>
                    <td className="py-2 text-slate-400 text-[11px]">SQLite WASM + OPFS</td>
                    <td className="py-2 text-right">
                      <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-500/20 text-emerald-400">
                        HEALTHY
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Tab: Sync Outbox */}
      {activeTab === 'outbox' && (
        <div className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xl space-y-3">
          <div className="flex justify-between items-center">
            <h3 className="font-bold text-sm text-slate-900 dark:text-white">
              SQLite sync_outbox Table (Durable Write-Ahead Offline Queue)
            </h3>
            <button
              onClick={() => db.triggerSyncNow()}
              disabled={!db.isOnline || db.isSyncing}
              className="px-3 py-1 bg-cyan-600 hover:bg-cyan-500 text-white rounded-lg text-xs font-bold transition disabled:opacity-50"
            >
              {db.isSyncing ? 'Syncing...' : 'Flush Outbox to Cloud'}
            </button>
          </div>

          {outboxRows.length === 0 ? (
            <div className="py-8 text-center text-slate-400 text-xs">
              Outbox is currently empty. All offline changes are committed or already synchronized.
            </div>
          ) : (
            <div className="overflow-x-auto max-h-96">
              <table className="w-full text-xs text-left">
                <thead className="text-[11px] text-slate-500 border-b border-slate-200 dark:border-slate-800">
                  <tr>
                    <th className="pb-2">Operation</th>
                    <th className="pb-2">Entity</th>
                    <th className="pb-2">Entity ID</th>
                    <th className="pb-2">Status</th>
                    <th className="pb-2">Idempotency Key</th>
                    <th className="pb-2">Created At</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 font-mono text-[11px]">
                  {outboxRows.map(row => (
                    <tr key={row.id}>
                      <td className="py-2 text-purple-400 font-bold">{row.operation}</td>
                      <td className="py-2 text-cyan-400">{row.entity}</td>
                      <td className="py-2 text-slate-300">{row.entity_id}</td>
                      <td className="py-2">
                        <span
                          className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                            row.status === 'SYNCED'
                              ? 'bg-emerald-500/20 text-emerald-400'
                              : row.status === 'PENDING'
                              ? 'bg-cyan-500/20 text-cyan-400'
                              : 'bg-rose-500/20 text-rose-400'
                          }`}
                        >
                          {row.status}
                        </span>
                      </td>
                      <td className="py-2 text-slate-400 truncate max-w-xs" title={row.idempotency_key}>
                        {row.idempotency_key}
                      </td>
                      <td className="py-2 text-slate-400">{row.created_at?.substring(11, 19)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* Tab: SQL Query Runner */}
      {activeTab === 'sql' && (
        <div className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xl space-y-3">
          <h3 className="font-bold text-sm text-slate-900 dark:text-white">
            Direct SQLite WASM SQL Console
          </h3>
          <div className="flex gap-2">
            <input
              type="text"
              value={customSql}
              onChange={e => setCustomSql(e.target.value)}
              placeholder="e.g. SELECT * FROM students LIMIT 5;"
              className="flex-1 bg-slate-950 text-white font-mono text-xs px-3.5 py-2 rounded-xl border border-slate-700 focus:outline-none focus:border-cyan-500"
            />
            <button
              onClick={handleExecuteCustomSql}
              disabled={isExecutingSql}
              className="px-4 py-2 bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-bold rounded-xl transition"
            >
              {isExecutingSql ? 'Running...' : 'Run SQL'}
            </button>
          </div>

          {customSqlResult && (
            <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 text-xs font-mono max-h-72 overflow-auto">
              <pre className="text-emerald-400">{JSON.stringify(customSqlResult, null, 2)}</pre>
            </div>
          )}
        </div>
      )}

      {/* Tab: Bulk Test */}
      {activeTab === 'bulk' && (
        <div className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xl space-y-4 text-xs">
          <div>
            <h3 className="font-bold text-sm text-slate-900 dark:text-white">
              Offline Stress & Durability Verification
            </h3>
            <p className="text-slate-500 dark:text-slate-400 mt-1">
              Tests inserting 500+ students and 500 outbox records in ONE atomic SQLite transaction while completely offline.
            </p>
          </div>

          <button
            onClick={handleGenerate500Students}
            disabled={isGeneratingBulk}
            className="px-4 py-2.5 bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-bold rounded-xl text-xs shadow-lg transition flex items-center gap-2"
          >
            <Sparkles className="w-4 h-4" />
            {isGeneratingBulk ? 'Inserting 500 Students...' : 'Create 500 Students Offline (1 Transaction)'}
          </button>

          {bulkStatus && (
            <div className="p-3 rounded-xl bg-slate-100 dark:bg-slate-950 border border-slate-300 dark:border-slate-800 font-mono text-cyan-600 dark:text-cyan-400">
              {bulkStatus}
            </div>
          )}
        </div>
      )}
    </div>
  );
};

