import React, { useState } from 'react';
import {
  Laptop,
  Key,
  ShieldCheck,
  CheckCircle2,
  AlertCircle,
  Building,
  ArrowRight,
  Database,
  Sparkles,
  Lock,
  Cpu,
} from 'lucide-react';
import { db } from '../../db/localDatabase';

// ----------------------------------------------------
// Screen: Device Activation Screen (Part 1 of Image 2)
// ----------------------------------------------------
interface DeviceActivationProps {
  onSuccess: () => void;
}

export const DeviceActivationScreen: React.FC<DeviceActivationProps> = ({ onSuccess }) => {
  const [licenseId, setLicenseId] = useState('LIC-8F72K91');
  const [activationCode, setActivationCode] = useState('ACT-9921-8842');
  const [deviceId] = useState('DEVICE-7A91X'); // Auto-generated by application
  const [isVerifying, setIsVerifying] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');

  const handleActivate = (e: React.FormEvent) => {
    e.preventDefault();
    setIsVerifying(true);
    setErrorMsg('');

    setTimeout(() => {
      // Validate credentials against management authority
      if (!licenseId.trim() || !activationCode.trim()) {
        setErrorMsg('Please enter both License ID and Activation Code.');
        setIsVerifying(false);
        return;
      }

      const res = db.activateDevice(licenseId.trim(), activationCode.trim());
      setIsVerifying(false);

      if (res.success) {
        onSuccess();
      } else {
        setErrorMsg(res.message || 'Invalid activation credentials.');
      }
    }, 900);
  };

  return (
    <div className="max-w-lg mx-auto py-12 px-4 space-y-6 animate-in fade-in duration-300">
      {/* Header */}
      <div className="text-center space-y-2">
        <div className="w-16 h-16 rounded-2xl bg-gradient-to-tr from-cyan-500 to-blue-600 flex items-center justify-center mx-auto shadow-2xl shadow-cyan-500/30">
          <Key className="w-8 h-8 text-white" />
        </div>
        <h1 className="text-2xl font-extrabold text-slate-900 dark:text-white">
          Device License Activation
        </h1>
        <p className="text-xs text-slate-600 dark:text-slate-400">
          PART 1 — Library Purchase → Device Authorization Workflow
        </p>
      </div>

      {/* Form Container */}
      <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700/80 shadow-2xl space-y-4 text-xs">
        {errorMsg && (
          <div className="p-3 rounded-xl bg-rose-50 dark:bg-rose-500/10 border border-rose-300 dark:border-rose-500/30 text-rose-700 dark:text-rose-400 flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>{errorMsg}</span>
          </div>
        )}

        <form onSubmit={handleActivate} className="space-y-4">
          <div>
            <label className="block text-slate-700 dark:text-slate-300 mb-1 font-semibold">
              License ID (Provided on Purchase) *
            </label>
            <input
              type="text"
              placeholder="e.g. LIC-8F72K91"
              value={licenseId}
              onChange={e => setLicenseId(e.target.value)}
              className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-xl px-3.5 py-2.5 text-slate-900 dark:text-white font-mono font-bold focus:border-cyan-500 focus:outline-none"
            />
            <span className="text-[10px] text-slate-500 mt-1 block">
              Demo valid: <b className="text-cyan-500">LIC-8F72K91</b> or <b className="text-cyan-500">LIC-000001</b>
            </span>
          </div>

          <div>
            <label className="block text-slate-700 dark:text-slate-300 mb-1 font-semibold">
              Activation Code *
            </label>
            <input
              type="text"
              placeholder="e.g. ACT-9921-8842"
              value={activationCode}
              onChange={e => setActivationCode(e.target.value)}
              className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-xl px-3.5 py-2.5 text-slate-900 dark:text-white font-mono focus:border-cyan-500 focus:outline-none"
            />
          </div>

          {/* Auto-Generated Device ID */}
          <div className="p-3.5 rounded-xl bg-slate-100 dark:bg-slate-950/70 border border-slate-200 dark:border-slate-800 space-y-1">
            <span className="text-[10px] uppercase tracking-wider font-bold text-slate-500 dark:text-slate-400 block">
              Auto-Generated Device Identifier
            </span>
            <div className="flex justify-between items-center">
              <span className="font-mono text-sm font-bold text-cyan-600 dark:text-cyan-400">
                {deviceId}
              </span>
              <span className="text-[10px] text-slate-500 font-medium">Hardware Bound</span>
            </div>
            <p className="text-[9px] text-slate-500">
              Unique machine fingerprint. Customer does not need to enter this manually.
            </p>
          </div>

          <button
            type="submit"
            disabled={isVerifying}
            className="w-full py-3 bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-bold rounded-xl shadow-lg shadow-cyan-500/20 text-xs transition flex items-center justify-center gap-2 disabled:opacity-50"
          >
            {isVerifying ? (
              <>Verifying with Management Server...</>
            ) : (
              <>
                <ShieldCheck className="w-4 h-4" />
                Activate Device & Store License Token
              </>
            )}
          </button>
        </form>

        <div className="pt-3 border-t border-slate-200 dark:border-slate-800 text-[11px] text-slate-500 space-y-1">
          <div className="flex items-center gap-1.5">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
            <span>Internet required only for initial device registration</span>
          </div>
          <div className="flex items-center gap-1.5">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
            <span>Signed Token stored in secure local storage for offline operation</span>
          </div>
        </div>
      </div>
    </div>
  );
};

// ----------------------------------------------------
// Screen 61: Developer Database Inspector (library.db)
// ----------------------------------------------------
export const LocalDatabaseInspectorScreen: React.FC = () => {
  const [integrityStatus, setIntegrityStatus] = useState<string | null>(null);
  const [folderOpenNotice, setFolderOpenNotice] = useState(false);

  const tables = [
    { name: 'associations', count: db.associations.length, size: '24 KB' },
    { name: 'licenses', count: 3, size: '12 KB' },
    { name: 'devices', count: db.devices.length, size: '16 KB' },
    { name: 'users', count: db.users.length, size: '32 KB' },
    { name: 'roles', count: 5, size: '8 KB' },
    { name: 'permissions', count: 48, size: '18 KB' },
    { name: 'students', count: db.students.length, size: '1.8 MB' },
    { name: 'admissions', count: db.admissions.length, size: '512 KB' },
    { name: 'memberships', count: 1248, size: '1.2 MB' },
    { name: 'rooms', count: db.rooms.length, size: '16 KB' },
    { name: 'seats', count: db.seats.length, size: '780 KB' },
    { name: 'attendance', count: db.attendance.length, size: '4.5 MB' },
    { name: 'payments', count: db.payments.length, size: '1.4 MB' },
    { name: 'receipts', count: db.payments.length, size: '640 KB' },
    { name: 'lockers', count: db.lockers.length, size: '28 KB' },
    { name: 'visitors', count: db.visitors.length, size: '180 KB' },
    { name: 'complaints', count: db.complaints.length, size: '92 KB' },
    { name: 'notices', count: db.notices.length, size: '44 KB' },
    { name: 'staff', count: db.staff.length, size: '22 KB' },
    { name: 'expenses', count: db.expenses.length, size: '310 KB' },
    { name: 'sync_queue', count: db.syncQueue.length, size: '128 KB' },
    { name: 'audit_logs', count: db.auditLogs.length, size: '620 KB' },
  ];

  const handleIntegrityCheck = () => {
    setIntegrityStatus('Checking PRAGMA integrity_check...');
    setTimeout(() => {
      setIntegrityStatus('✓ PRAGMA integrity_check: ok — Zero corruption detected across all 28 tables.');
    }, 600);
  };

  const handleOpenFolder = () => {
    setFolderOpenNotice(true);
    setTimeout(() => setFolderOpenNotice(false), 4000);
  };

  return (
    <div className="space-y-5 pb-8 animate-in fade-in duration-300">
      {/* Header */}
      <div className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700/70 shadow-xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-xl font-extrabold text-slate-900 dark:text-white flex items-center gap-2">
            <Database className="w-5 h-5 text-cyan-500" />
            Local SQLite Database Inspector (`library.db`)
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
            Developer-grade operational database viewer, PRAGMA checks, and table inspection
          </p>
        </div>

        <div className="flex gap-2">
          <button
            onClick={handleIntegrityCheck}
            className="px-3.5 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-xs font-semibold shadow transition flex items-center gap-1.5"
          >
            <ShieldCheck className="w-4 h-4" />
            Run Integrity Check
          </button>
          <button
            onClick={handleOpenFolder}
            className="px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs font-semibold border border-slate-700 transition"
          >
            Open Database Folder
          </button>
        </div>
      </div>

      {folderOpenNotice && (
        <div className="p-3.5 rounded-xl bg-cyan-50 dark:bg-cyan-950/40 border border-cyan-300 dark:border-cyan-800 text-cyan-800 dark:text-cyan-300 text-xs flex items-center gap-2">
          <Database className="w-4 h-4" />
          <span>Local storage path: <b>App Data/library-management/database/library.db</b></span>
        </div>
      )}

      {integrityStatus && (
        <div className="p-3.5 rounded-xl bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-300 dark:border-emerald-800 text-emerald-800 dark:text-emerald-300 text-xs font-mono flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4" />
          <span>{integrityStatus}</span>
        </div>
      )}

      {/* Database KPI Metadata */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-xs">
        <div className="p-4 rounded-xl bg-white dark:bg-slate-900/90 border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-slate-500 dark:text-slate-400 block">Database Status</span>
          <span className="font-bold text-emerald-600 dark:text-emerald-400 text-sm mt-1 flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-emerald-400" />
            Connected & Authoritative
          </span>
        </div>

        <div className="p-4 rounded-xl bg-white dark:bg-slate-900/90 border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-slate-500 dark:text-slate-400 block">SQLite Engine Version</span>
          <span className="font-bold text-slate-900 dark:text-white text-sm mt-1 font-mono">
            SQLite 3.45.1 (WAL Mode)
          </span>
        </div>

        <div className="p-4 rounded-xl bg-white dark:bg-slate-900/90 border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-slate-500 dark:text-slate-400 block">Database File Size</span>
          <span className="font-bold text-slate-900 dark:text-white text-sm mt-1 font-mono">
            12.8 MB (Optimized)
          </span>
        </div>

        <div className="p-4 rounded-xl bg-white dark:bg-slate-900/90 border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-slate-500 dark:text-slate-400 block">Pending Sync Queue</span>
          <span className="font-bold text-cyan-600 dark:text-cyan-400 text-sm mt-1 font-mono">
            {db.syncQueue.length} Operations
          </span>
        </div>
      </div>

      {/* Tables List */}
      <div className="p-5 rounded-2xl bg-white dark:bg-slate-900/90 border border-slate-200 dark:border-slate-700/70 shadow-xl overflow-hidden">
        <h3 className="font-bold text-sm text-slate-900 dark:text-white mb-3">
          Local Tables Schema (28 Tables)
        </h3>

        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left">
            <thead className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 border-b border-slate-200 dark:border-slate-800">
              <tr>
                <th className="pb-2.5">Table Name</th>
                <th className="pb-2.5">Record Count</th>
                <th className="pb-2.5">Approx. Size</th>
                <th className="pb-2.5">Indexed Keys</th>
                <th className="pb-2.5 text-right">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60">
              {tables.map(tbl => (
                <tr key={tbl.name} className="hover:bg-slate-50 dark:hover:bg-slate-800/40 transition">
                  <td className="py-2.5 font-mono font-bold text-cyan-600 dark:text-cyan-400">
                    {tbl.name}
                  </td>
                  <td className="py-2.5 font-mono font-semibold text-slate-800 dark:text-slate-200">
                    {tbl.count} rows
                  </td>
                  <td className="py-2.5 text-slate-500 dark:text-slate-400 font-mono text-[11px]">
                    {tbl.size}
                  </td>
                  <td className="py-2.5 text-slate-500 dark:text-slate-400">
                    id, association_id, updated_at
                  </td>
                  <td className="py-2.5 text-right">
                    <span className="px-2 py-0.5 rounded text-[10px] font-semibold bg-emerald-100 dark:bg-emerald-500/20 text-emerald-700 dark:text-emerald-300">
                      Healthy
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
