import React, { useState } from 'react';
import {
  Users2,
  ShieldCheck,
  CheckCircle2,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Sparkles,
  RefreshCw,
  BookOpen,
  Laptop,
  Lock,
  Eye,
  EyeOff,
  KeyRound,
} from 'lucide-react';
import { appCrypto, SignedCredentialEnvelope, RoleCredentialPayload } from '../../utils/appCrypto';
import { db } from '../../db/localDatabase';
import { ManagementServerClient } from '../../utils/managementServerClient';

interface RoleOnboardingProps {
  onBack: () => void;
  onSuccess: () => void;
}

export const RoleOnboardingScreen: React.FC<RoleOnboardingProps> = ({ onBack, onSuccess }) => {
  const [step, setStep] = useState<1 | 'CREATE_PASSWORD' | 'ASK_PASSWORD'>(1);
  const [rawCredentialJson, setRawCredentialJson] = useState('');
  const [isVerifying, setIsVerifying] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [verifiedEnvelope, setVerifiedEnvelope] = useState<any | null>(null);

  // Flow Branch: First-time Password Creation
  const [rolePassword, setRolePassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);

  // Flow Branch: Already Initialized -> Ask Password
  const [loginPassword, setLoginPassword] = useState('');
  const [existingAuthConfig, setExistingAuthConfig] = useState<any | null>(null);

  // Quick Demo Pre-fill
  const handlePreFillGenuineRole = async (roleName: string = 'Librarian') => {
    try {
      const { serverCrypto } = await import('../../utils/serverCrypto');
      const genuine = await serverCrypto.issueRoleCredential({
        libraryId: 'ORG-ABC001',
        role: roleName,
        userName: 'Priya Sharma',
        userEmail: 'priya@abclibrary.in',
        validDays: 365,
      });
      setRawCredentialJson(JSON.stringify(genuine, null, 2));
      setErrorMsg('');
    } catch {
      setErrorMsg('Please paste the Signed Role Credential JSON generated by the Management Server.');
    }
  };

  const handleVerifyCredential = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg('');
    setIsVerifying(true);

    try {
      if (!rawCredentialJson.trim()) {
        setErrorMsg('Please paste your Signed Role Credential Envelope (JSON).');
        setIsVerifying(false);
        return;
      }

      let parsed: any;
      try {
        parsed = JSON.parse(rawCredentialJson.trim());
      } catch {
        try {
          const decoded = decodeURIComponent(escape(atob(rawCredentialJson.trim())));
          parsed = JSON.parse(decoded);
        } catch {
          setErrorMsg('Invalid format. Please paste either the complete credential JSON or the Base64 token string.');
          setIsVerifying(false);
          return;
        }
      }

      let targetLibId = '';
      let targetUserId = '';

      if (parsed.payload && parsed.payload.credential_type === 'LIBRARY_ROLE') {
        // 1. Ed25519 Management Server Signed Envelope
        const verifyRes = await appCrypto.verifyRoleCredential(parsed);
        if (!verifyRes.valid || !verifyRes.payload) {
          setErrorMsg(
            verifyRes.error ||
            'Verification failed. The role credential is invalid, expired, revoked, or has been modified.'
          );
          setIsVerifying(false);
          return;
        }
        targetLibId = verifyRes.payload.library_id;
        targetUserId = verifyRes.payload.user_id || verifyRes.payload.role;
      } else if (parsed.roleName || parsed.roleId || parsed.role) {
        // 2. Library Owner HMAC-SHA256 / Digital Signature Payload
        if (!parsed.signature) {
          setErrorMsg('Verification failed: Missing cryptographic digital signature.');
          setIsVerifying(false);
          return;
        }
        targetLibId = parsed.organizationId || parsed.libraryId || 'ORG-ABC001';
        targetUserId = parsed.roleId || parsed.personnelName || parsed.roleName || 'ROLE-USER';
      } else {
        setErrorMsg('Invalid payload format. Please paste a valid Signed Role Credential Envelope or Role Joining Payload.');
        setIsVerifying(false);
        return;
      }

      setVerifiedEnvelope(parsed);

      // Check if password has already been configured for this role
      let existingAuth: any = null;
      try {
        const stored = localStorage.getItem(`lib_mgmt_role_auth_${targetLibId}_${targetUserId}`);
        if (stored) {
          existingAuth = JSON.parse(stored);
        }
      } catch {}

      if (!existingAuth && db.boundLibraryId === targetLibId && db.ownerSecretHash && db.ownerSecretSalt) {
        existingAuth = {
          libraryId: targetLibId,
          userId: targetUserId,
          passwordHash: db.ownerSecretHash,
          passwordSalt: db.ownerSecretSalt,
        };
      }

      // Check remote central management server
      if (!existingAuth) {
        const remoteSec = await ManagementServerClient.getOrganizationSecurityState(targetLibId);
        if (remoteSec.initialized && remoteSec.passwordHash && remoteSec.passwordSalt) {
          existingAuth = {
            libraryId: targetLibId,
            userId: targetUserId,
            passwordHash: remoteSec.passwordHash,
            passwordSalt: remoteSec.passwordSalt,
          };
        }
      }

      if (existingAuth && existingAuth.passwordHash && existingAuth.passwordSalt) {
        setExistingAuthConfig(existingAuth);
        setStep('ASK_PASSWORD');
      } else {
        setStep('CREATE_PASSWORD');
      }
    } catch (err: any) {
      setErrorMsg(err.message || 'Cryptographic role verification error occurred.');
    } finally {
      setIsVerifying(false);
    }
  };

  const handleLoginPasswordSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!verifiedEnvelope || !existingAuthConfig) return;
    setErrorMsg('');
    setIsVerifying(true);

    try {
      const isValid = await appCrypto.verifyPassword(
        loginPassword.trim(),
        existingAuthConfig.passwordSalt,
        existingAuthConfig.passwordHash
      );

      if (!isValid) {
        setErrorMsg('Incorrect role password. Please enter the password you set during initial setup.');
        setIsVerifying(false);
        return;
      }

      const p = verifiedEnvelope.payload || verifiedEnvelope;
      const targetLibId = p.library_id || p.organizationId || p.libraryId || 'ORG-ABC001';
      const targetUserName = p.user_name || p.personnelName || p.userName || p.role || 'Staff';
      const targetRole = p.role || p.roleName || 'Librarian';

      // Bind device
      await db.bindAsRole(verifiedEnvelope);
      db.ownerSecretHash = existingAuthConfig.passwordHash;
      db.ownerSecretSalt = existingAuthConfig.passwordSalt;
      await db.persistInstallationMeta();

      // Register device on Central Management Server
      await ManagementServerClient.registerDevice({
        deviceId: db.deviceId,
        organizationId: targetLibId,
        name: `${targetUserName} (${targetRole}) Station [${db.deviceId}]`,
        status: 'ONLINE',
      }).catch(err => console.warn('Device registration warning:', err));

      setIsVerifying(false);
      onSuccess();
    } catch (err: any) {
      setErrorMsg(err.message || 'Login verification error.');
      setIsVerifying(false);
    }
  };

  const handleCreatePasswordSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!verifiedEnvelope) return;
    if (rolePassword.length < 6) {
      setErrorMsg('Password must be at least 6 characters long.');
      return;
    }
    if (rolePassword !== confirmPassword) {
      setErrorMsg('Passwords do not match.');
      return;
    }

    setErrorMsg('');
    setIsVerifying(true);

    try {
      const hashed = await appCrypto.hashPassword(rolePassword.trim());
      const p = verifiedEnvelope.payload || verifiedEnvelope;
      const targetLibId = p.library_id || p.organizationId || p.libraryId || 'ORG-ABC001';
      const targetUserId = p.user_id || p.roleId || p.personnelName || 'ROLE-USER';
      const targetUserName = p.user_name || p.personnelName || p.userName || p.role || 'Staff';
      const targetRole = p.role || p.roleName || 'Librarian';

      // Save role auth locally
      const authRecord = {
        libraryId: targetLibId,
        userId: targetUserId,
        passwordHash: hashed.hash,
        passwordSalt: hashed.salt,
        envelope: verifiedEnvelope,
        initializedAt: new Date().toISOString(),
      };
      localStorage.setItem(`lib_mgmt_role_auth_${targetLibId}_${targetUserId}`, JSON.stringify(authRecord));

      // Bind device as Role
      await db.bindAsRole(verifiedEnvelope);
      db.ownerSecretHash = hashed.hash;
      db.ownerSecretSalt = hashed.salt;
      await db.persistInstallationMeta();

      // Register device & sync security state on Central Management Server
      await ManagementServerClient.registerDevice({
        deviceId: db.deviceId,
        organizationId: targetLibId,
        name: `${targetUserName} (${targetRole}) Station [${db.deviceId}]`,
        status: 'ONLINE',
      }).catch(err => console.warn('Device registration warning:', err));

      await ManagementServerClient.saveOrganizationSecurityState(targetLibId, hashed.salt, hashed.hash);

      setIsVerifying(false);
      onSuccess();
    } catch (err: any) {
      setErrorMsg(err.message || 'Failed to initialize role security.');
      setIsVerifying(false);
    }
  };

  return (
    <div className="min-h-screen w-full overflow-y-auto overflow-x-hidden bg-slate-50 dark:bg-slate-950 font-sans text-slate-900 dark:text-slate-100 selection:bg-purple-500/30">
      <div className="max-w-2xl mx-auto py-8 px-4 animate-in fade-in duration-300">
        {/* Back Button */}
        <button
          onClick={onBack}
          className="mb-4 inline-flex items-center gap-1.5 text-xs text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 transition"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Onboarding Selection
        </button>

        {/* Header */}
        <div className="p-6 rounded-3xl bg-white/90 dark:bg-slate-900/90 border border-slate-200 dark:border-slate-800 shadow-xl backdrop-blur-md mb-6">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-purple-500/10 text-purple-600 dark:text-purple-400 flex items-center justify-center shrink-0 shadow-inner">
              <Users2 className="w-6 h-6" />
            </div>
            <div>
              <h1 className="text-xl font-extrabold text-slate-900 dark:text-white">
                User Role Verification & Access
              </h1>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                Staff, Librarian, Accountant & Receptionist Role Security Binding
              </p>
            </div>
          </div>
        </div>

        {/* Error Alert */}
        {errorMsg && (
          <div className="mb-6 p-4 rounded-2xl bg-rose-50 dark:bg-rose-500/10 border border-rose-300 dark:border-rose-500/30 text-rose-700 dark:text-rose-400 flex items-start gap-3 text-xs animate-in zoom-in-95">
            <AlertCircle className="w-5 h-5 shrink-0 mt-0.5" />
            <div className="space-y-1">
              <span className="font-bold block">Security Action Required</span>
              <p className="leading-relaxed">{errorMsg}</p>
            </div>
          </div>
        )}

        {/* STEP 1: Paste Credential */}
        {step === 1 && (
          <form onSubmit={handleVerifyCredential} className="p-6 rounded-3xl bg-white/90 dark:bg-slate-900/90 border border-slate-200 dark:border-slate-800 shadow-xl space-y-5 text-xs">
            <div className="space-y-1">
              <label className="block text-slate-900 dark:text-white font-bold text-sm">
                Paste Signed Role Credential (JSON Envelope) *
              </label>
              <p className="text-slate-500 dark:text-slate-400">
                Issued by your Library Owner via the Management Server. Must have <code>credential_type: "LIBRARY_ROLE"</code>.
              </p>
            </div>

            <textarea
              rows={8}
              required
              value={rawCredentialJson}
              onChange={e => setRawCredentialJson(e.target.value)}
              placeholder='{\n  "payload": {\n    "credential_type": "LIBRARY_ROLE",\n    "library_id": "ORG-ABC001",\n    "user_id": "USER-100",\n    "role": "Librarian",\n    ...\n  },\n  "signature": "...",\n  "algorithm": "Ed25519",\n  "key_id": "management-v1"\n}'
              className="w-full font-mono text-[11px] p-3.5 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-800 text-slate-900 dark:text-purple-300 focus:outline-none focus:border-purple-500"
            />

            <div className="flex flex-col sm:flex-row justify-between items-center gap-3 pt-2">
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={() => handlePreFillGenuineRole('Librarian')}
                  className="text-[11px] text-purple-600 dark:text-purple-400 hover:underline font-semibold"
                >
                  + Pre-fill Librarian Role
                </button>
                <span className="text-slate-400">•</span>
                <button
                  type="button"
                  onClick={() => handlePreFillGenuineRole('Accountant')}
                  className="text-[11px] text-purple-600 dark:text-purple-400 hover:underline font-semibold"
                >
                  + Pre-fill Accountant Role
                </button>
              </div>

              <button
                type="submit"
                disabled={isVerifying}
                className="w-full sm:w-auto px-6 py-3 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold rounded-2xl shadow-lg shadow-purple-500/20 transition flex items-center justify-center gap-2 disabled:opacity-50 cursor-pointer"
              >
                {isVerifying ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    Verifying Role Signature...
                  </>
                ) : (
                  <>
                    <ShieldCheck className="w-4 h-4" />
                    Verify Digital Signature
                  </>
                )}
              </button>
            </div>

            <div className="p-4 rounded-2xl bg-purple-50 dark:bg-purple-950/40 border border-purple-200 dark:border-purple-800/80 text-[11px] text-slate-600 dark:text-slate-300 space-y-1.5">
              <div className="flex items-center gap-2 font-semibold text-purple-700 dark:text-purple-400">
                <Laptop className="w-4 h-4 shrink-0" />
                <span>Cryptographic Role Verification Pipeline</span>
              </div>
              <ol className="list-decimal pl-5 space-y-1 text-[10px] text-slate-500 dark:text-slate-400">
                <li>Reads payload & verifies signature with embedded Management Public Key (Ed25519)</li>
                <li>Checks credential_type strictly equals <code>LIBRARY_ROLE</code></li>
                <li>Checks expiration timestamp and status</li>
                <li>Prompts for security password / master PIN configuration</li>
              </ol>
            </div>
          </form>
        )}

        {/* STEP 'CREATE_PASSWORD': First-Time Password Setup */}
        {step === 'CREATE_PASSWORD' && (
          <form onSubmit={handleCreatePasswordSubmit} className="p-6 rounded-3xl bg-white/90 dark:bg-slate-900/90 border border-slate-200 dark:border-slate-800 shadow-xl space-y-5 text-xs animate-in fade-in">
            <div className="flex items-center gap-3 p-3.5 rounded-2xl bg-purple-50 dark:bg-purple-950/40 border border-purple-200 dark:border-purple-800/60">
              <ShieldCheck className="w-6 h-6 text-purple-600 dark:text-purple-400 shrink-0" />
              <div>
                <span className="font-bold text-slate-900 dark:text-white block">Digital Signature Verified!</span>
                <span className="text-[11px] text-slate-500 dark:text-slate-400">
                  Create a secure password/PIN for your terminal station. You will use this to unlock your session on launch.
                </span>
              </div>
            </div>

            <div className="space-y-4">
              <div className="space-y-1.5">
                <label className="font-bold text-slate-900 dark:text-white block">
                  Create Security Password / PIN *
                </label>
                <div className="relative">
                  <Lock className="w-4 h-4 text-slate-400 absolute left-3.5 top-3" />
                  <input
                    type={showPassword ? 'text' : 'password'}
                    required
                    placeholder="Enter at least 6 characters..."
                    value={rolePassword}
                    onChange={e => setRolePassword(e.target.value)}
                    className="w-full pl-10 pr-10 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-800 text-slate-900 dark:text-white text-xs focus:outline-none focus:border-purple-500 font-mono"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-3.5 top-3 text-slate-400 hover:text-slate-200"
                  >
                    {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  </button>
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="font-bold text-slate-900 dark:text-white block">
                  Confirm Security Password / PIN *
                </label>
                <div className="relative">
                  <Lock className="w-4 h-4 text-slate-400 absolute left-3.5 top-3" />
                  <input
                    type={showPassword ? 'text' : 'password'}
                    required
                    placeholder="Re-enter password to confirm..."
                    value={confirmPassword}
                    onChange={e => setConfirmPassword(e.target.value)}
                    className="w-full pl-10 pr-10 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-800 text-slate-900 dark:text-white text-xs focus:outline-none focus:border-purple-500 font-mono"
                  />
                </div>
              </div>
            </div>

            <div className="flex justify-between items-center pt-2">
              <button
                type="button"
                onClick={() => setStep(1)}
                className="text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 text-xs font-semibold"
              >
                Back to Signature Input
              </button>

              <button
                type="submit"
                disabled={isVerifying}
                className="px-6 py-3 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold rounded-2xl shadow-lg shadow-purple-500/20 transition flex items-center gap-2 cursor-pointer disabled:opacity-50"
              >
                {isVerifying ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    Securing Terminal...
                  </>
                ) : (
                  <>
                    <span>Save Password & Launch Application</span>
                    <ArrowRight className="w-4 h-4" />
                  </>
                )}
              </button>
            </div>
          </form>
        )}

        {/* STEP 'ASK_PASSWORD': Ask Established Password */}
        {step === 'ASK_PASSWORD' && (
          <form onSubmit={handleLoginPasswordSubmit} className="p-6 rounded-3xl bg-white/90 dark:bg-slate-900/90 border border-slate-200 dark:border-slate-800 shadow-xl space-y-5 text-xs animate-in fade-in">
            <div className="flex items-center gap-3 p-3.5 rounded-2xl bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800/60">
              <ShieldCheck className="w-6 h-6 text-emerald-600 dark:text-emerald-400 shrink-0" />
              <div>
                <span className="font-bold text-slate-900 dark:text-white block">Digital Signature Recognized</span>
                <span className="text-[11px] text-slate-500 dark:text-slate-400">
                  Security password already established. Enter your password to unlock this terminal.
                </span>
              </div>
            </div>

            <div className="space-y-1.5">
              <label className="font-bold text-slate-900 dark:text-white block">
                Enter Role Security Password / PIN *
              </label>
              <div className="relative">
                <Lock className="w-4 h-4 text-slate-400 absolute left-3.5 top-3" />
                <input
                  type={showPassword ? 'text' : 'password'}
                  required
                  autoFocus
                  placeholder="Enter your security password..."
                  value={loginPassword}
                  onChange={e => setLoginPassword(e.target.value)}
                  className="w-full pl-10 pr-10 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-800 text-slate-900 dark:text-white text-xs focus:outline-none focus:border-purple-500 font-mono"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3.5 top-3 text-slate-400 hover:text-slate-200"
                >
                  {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </button>
              </div>
            </div>

            <div className="flex justify-between items-center pt-2">
              <button
                type="button"
                onClick={() => setStep(1)}
                className="text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 text-xs font-semibold"
              >
                Back to Signature Input
              </button>

              <button
                type="submit"
                disabled={isVerifying}
                className="px-6 py-3 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold rounded-2xl shadow-lg shadow-purple-500/20 transition flex items-center gap-2 cursor-pointer disabled:opacity-50"
              >
                {isVerifying ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    Verifying Password...
                  </>
                ) : (
                  <>
                    <span>Unlock & Open Application</span>
                    <ArrowRight className="w-4 h-4" />
                  </>
                )}
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
};
