import {
  Association,
  User,
  Room,
  Seat,
  SeatStatus,
  Student,
  Admission,
  MembershipPlan,
  AttendanceRecord,
  PaymentTransaction,
  SeatReservation,
  Locker,
  LeaveRequest,
  Visitor,
  Complaint,
  Notice,
  StaffMember,
  Expense,
  Income,
  DeviceInfo,
  AppNotification,
  AuditLog,
} from '../types';

export const initialAssociations: Association[] = [
  {
    id: 'assoc-1',
    name: 'Knowledge Library (Main Campus)',
    code: 'KL-01',
    owner: 'Rahul Sharma',
    phone: '+91 98765 43210',
    email: 'admin@knowledgelibrary.com',
    address: 'Plot 42, Knowledge Corridor, Near Metro Gate 3',
    city: 'Jaipur',
    state: 'Rajasthan',
    gst: '08AAAAA0000A1Z5',
    totalSeats: 1100,
    totalRooms: 4,
    activeStudents: 1186,
    monthlyRevenue: 1485000,
    currency: '₹',
    timezone: 'IST (UTC+05:30)',
  },
  {
    id: 'assoc-2',
    name: 'Saraswati Self-Study Zone',
    code: 'SSZ-02',
    owner: 'Vikram Meena',
    phone: '+91 98234 56789',
    email: 'contact@saraswatistudy.in',
    address: 'Opp. University South Campus',
    city: 'Delhi',
    state: 'Delhi',
    gst: '07BBBBB1111B2Z6',
    totalSeats: 450,
    totalRooms: 3,
    activeStudents: 410,
    monthlyRevenue: 620000,
    currency: '₹',
    timezone: 'IST (UTC+05:30)',
  },
  {
    id: 'assoc-3',
    name: 'Apex Competitive Reading Room',
    code: 'ARR-03',
    owner: 'Priyanka Rathore',
    phone: '+91 94140 12345',
    email: 'apexreading@gmail.com',
    address: 'Sector 14, Education Hub',
    city: 'Indore',
    state: 'Madhya Pradesh',
    gst: '23CCCCC2222C3Z7',
    totalSeats: 600,
    totalRooms: 4,
    activeStudents: 540,
    monthlyRevenue: 850000,
    currency: '₹',
    timezone: 'IST (UTC+05:30)',
  },
];

export const initialUsers: User[] = [
  {
    id: 'usr-1',
    associationId: 'assoc-1',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@knowledgelibrary.com',
    role: 'Super Admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    pin: '1234',
    phone: '+91 98765 43210',
    status: 'Active',
  },
  {
    id: 'usr-2',
    associationId: 'assoc-1',
    name: 'Pooja Verma',
    email: 'pooja.manager@knowledgelibrary.com',
    role: 'Manager',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    pin: '2345',
    phone: '+91 98765 43211',
    status: 'Active',
  },
  {
    id: 'usr-3',
    associationId: 'assoc-1',
    name: 'Amit Joshi',
    email: 'amit.reception@knowledgelibrary.com',
    role: 'Receptionist',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    pin: '3456',
    phone: '+91 98765 43212',
    status: 'Active',
  },
];

export const initialRooms: Room[] = [
  {
    id: 'room-1',
    associationId: 'assoc-1',
    name: 'Room A - Main Reading Hall',
    floor: 'Ground Floor',
    capacity: 300,
    occupied: 245,
    type: 'Reading Hall',
    isAc: true,
    hasWifi: true,
    hasCctv: true,
    hasCharging: true,
    status: 'Active',
  },
  {
    id: 'room-2',
    associationId: 'assoc-1',
    name: 'Room B - AC Silent Zone',
    floor: '1st Floor',
    capacity: 250,
    occupied: 210,
    type: 'AC Silent',
    isAc: true,
    hasWifi: true,
    hasCctv: true,
    hasCharging: true,
    status: 'Active',
  },
  {
    id: 'room-3',
    associationId: 'assoc-1',
    name: 'Room C - UPSC / Competitive Exam Wing',
    floor: '2nd Floor',
    capacity: 300,
    occupied: 260,
    type: 'Exam Focus',
    isAc: true,
    hasWifi: true,
    hasCctv: true,
    hasCharging: true,
    status: 'Active',
  },
  {
    id: 'room-4',
    associationId: 'assoc-1',
    name: 'Room D - Digital Lounge & Cabin Cubicles',
    floor: '3rd Floor',
    capacity: 250,
    occupied: 177,
    type: 'Digital Lounge',
    isAc: true,
    hasWifi: true,
    hasCctv: true,
    hasCharging: true,
    status: 'Active',
  },
];

export const initialMembershipPlans: MembershipPlan[] = [
  {
    id: 'plan-1',
    associationId: 'assoc-1',
    name: '1 Month Standard',
    durationMonths: 1,
    price: 1000,
    discount: 0,
    description: 'General reading hall access with high-speed Wi-Fi and power socket.',
    seatType: 'Standard Desk',
    benefits: ['12 Hours Access', 'High Speed Wi-Fi', 'Filtered Water', 'Newspaper Zone'],
    active: true,
  },
  {
    id: 'plan-2',
    associationId: 'assoc-1',
    name: '3 Months Pro',
    durationMonths: 3,
    price: 2700,
    discount: 10,
    description: 'Reserved study space with personal locker and dedicated charging bay.',
    seatType: 'Cushioned Ergonomic',
    benefits: ['16 Hours Access', 'Free Locker Storage', 'Personal Charging Port', 'Silent AC Zone'],
    active: true,
  },
  {
    id: 'plan-3',
    associationId: 'assoc-1',
    name: '6 Months Premium',
    durationMonths: 6,
    price: 5000,
    discount: 15,
    description: 'Fixed reserved seat with LED lamp, ergonomic leatherette chair & locker.',
    seatType: 'Premium Fixed Cubicle',
    benefits: ['24x7 Unlimited Access', 'Fixed Dedicated Seat', 'Free Dedicated Locker', 'Tea/Coffee Lounge'],
    active: true,
  },
  {
    id: 'plan-4',
    associationId: 'assoc-1',
    name: '1 Year Lifetime Aspirant',
    durationMonths: 12,
    price: 9000,
    discount: 25,
    description: 'Top-tier dedicated cabin space for UPSC, NEET, CA and GATE aspirants.',
    seatType: 'Executive Study Pod',
    benefits: ['24x7 VIP Access', 'Permanent Reserved Seat', 'Free Locker + Printing (50pg/mo)', 'Discussions Room Access'],
    active: true,
  },
];

// Generate seats for Room A (A01 - A50) and other rooms
export const generateInitialSeats = (): Seat[] => {
  const seats: Seat[] = [];
  const statusCycle: SeatStatus[] = [
    'AVAILABLE', 'OCCUPIED', 'AVAILABLE', 'RESERVED', 'OCCUPIED',
    'OCCUPIED', 'AVAILABLE', 'OCCUPIED', 'AVAILABLE', 'MAINTENANCE',
    'OCCUPIED', 'AVAILABLE', 'OCCUPIED', 'OCCUPIED', 'BLOCKED',
    'AVAILABLE', 'OCCUPIED', 'AVAILABLE', 'AVAILABLE', 'OCCUPIED'
  ];

  const studentsSample = [
    { name: 'Pooja Sharma', id: 'STU-1024', mobile: '+91 98765 11001', plan: '6 Months' },
    { name: 'Amit Verma', id: 'STU-1025', mobile: '+91 98765 11002', plan: '3 Months' },
    { name: 'Sneha Patel', id: 'STU-1026', mobile: '+91 98765 11003', plan: '1 Year' },
    { name: 'Rohit Singh', id: 'STU-1027', mobile: '+91 98765 11004', plan: '6 Months' },
    { name: 'Neha Gupta', id: 'STU-1028', mobile: '+91 98765 11005', plan: '3 Months' },
    { name: 'Meena Sharma', id: 'STU-1029', mobile: '+91 98765 11006', plan: '6 Months' },
    { name: 'Vikash Kumar', id: 'STU-1030', mobile: '+91 98765 11007', plan: '3 Months' },
    { name: 'Anjali Singh', id: 'STU-1031', mobile: '+91 98765 11008', plan: '1 Year' },
    { name: 'Rohit Yadav', id: 'STU-1032', mobile: '+91 98765 11009', plan: '6 Months' },
    { name: 'Priya Desai', id: 'STU-1033', mobile: '+91 98765 11010', plan: '3 Months' },
  ];

  const rooms = [
    { id: 'room-1', prefix: 'A', count: 50 },
    { id: 'room-2', prefix: 'B', count: 50 },
    { id: 'room-3', prefix: 'C', count: 50 },
    { id: 'room-4', prefix: 'D', count: 50 },
  ];

  rooms.forEach((r) => {
    for (let i = 1; i <= r.count; i++) {
      const numStr = i < 10 ? `0${i}` : `${i}`;
      const seatNo = `${r.prefix}${numStr}`;
      const status = statusCycle[(i - 1) % statusCycle.length];
      const student = status === 'OCCUPIED' ? studentsSample[(i - 1) % studentsSample.length] : undefined;

      seats.push({
        id: `seat-${r.prefix.toLowerCase()}-${i}`,
        associationId: 'assoc-1',
        roomId: r.id,
        seatNumber: seatNo,
        row: r.prefix,
        column: ((i - 1) % 10) + 1,
        type: i % 4 === 0 ? 'Premium' : i % 5 === 0 ? 'Window View' : 'Standard',
        hasCharging: true,
        hasLamp: i % 2 === 0,
        hasLocker: i % 3 === 0,
        status: status,
        studentId: student?.id,
        studentName: student?.name,
        studentMobile: student?.mobile,
        membershipEnd: student ? '2025-05-28' : undefined,
      });
    }
  });

  return seats;
};

export const initialStudents: Student[] = [
  {
    id: 'stu-1',
    studentId: 'STU-1024',
    associationId: 'assoc-1',
    name: 'Pooja Sharma',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    mobile: '+91 98765 11001',
    email: 'pooja.sharma@gmail.com',
    gender: 'Female',
    dob: '2001-08-14',
    address: 'B-24, Shastri Nagar, Jaipur',
    fatherName: 'Ram Avatar Sharma',
    emergencyContact: '+91 98765 11000',
    idProofType: 'Aadhaar Card',
    idProofNumber: '7845-1290-3341',
    admissionDate: '2025-04-28',
    membershipPlan: '6 Months Premium',
    membershipStatus: 'Active',
    expiryDate: '2025-10-28',
    seatNumber: 'A12',
    roomId: 'room-1',
    balanceDue: 0,
  },
  {
    id: 'stu-2',
    studentId: 'STU-1025',
    associationId: 'assoc-1',
    name: 'Amit Verma',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    mobile: '+91 98765 11002',
    email: 'amit.verma99@gmail.com',
    gender: 'Male',
    dob: '1999-12-05',
    address: 'H-104, Malviya Nagar, Jaipur',
    fatherName: 'Sunil Verma',
    emergencyContact: '+91 98765 11099',
    idProofType: 'Aadhaar Card',
    idProofNumber: '4512-8923-9011',
    admissionDate: '2025-04-27',
    membershipPlan: '3 Months Pro',
    membershipStatus: 'Active',
    expiryDate: '2025-07-27',
    seatNumber: 'B07',
    roomId: 'room-2',
    balanceDue: 0,
  },
  {
    id: 'stu-3',
    studentId: 'STU-1026',
    associationId: 'assoc-1',
    name: 'Sneha Patel',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    mobile: '+91 98765 11003',
    email: 'sneha.patel.ca@outlook.com',
    gender: 'Female',
    dob: '2000-04-20',
    address: 'C-18, Raja Park, Jaipur',
    fatherName: 'Bhavesh Patel',
    emergencyContact: '+91 98765 11088',
    idProofType: 'Voter ID',
    idProofNumber: 'WBG9012341',
    admissionDate: '2025-04-26',
    membershipPlan: '1 Year Lifetime Aspirant',
    membershipStatus: 'Active',
    expiryDate: '2026-04-26',
    seatNumber: 'C15',
    roomId: 'room-3',
    balanceDue: 0,
  },
  {
    id: 'stu-4',
    studentId: 'STU-1027',
    associationId: 'assoc-1',
    name: 'Rohit Singh',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    mobile: '+91 98765 11004',
    email: 'rohit.singh.upsc@gmail.com',
    gender: 'Male',
    dob: '1998-06-11',
    address: 'Plot 77, Mansarovar, Jaipur',
    fatherName: 'Surendra Singh',
    emergencyContact: '+91 98765 11077',
    idProofType: 'Driving License',
    idProofNumber: 'RJ-14-2018-00912',
    admissionDate: '2025-04-25',
    membershipPlan: '6 Months Premium',
    membershipStatus: 'Active',
    expiryDate: '2025-10-25',
    seatNumber: 'A23',
    roomId: 'room-1',
    balanceDue: 0,
  },
  {
    id: 'stu-5',
    studentId: 'STU-1028',
    associationId: 'assoc-1',
    name: 'Neha Gupta',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    mobile: '+91 98765 11005',
    email: 'neha.gupta.gate@gmail.com',
    gender: 'Female',
    dob: '2002-01-18',
    address: 'Flat 302, Vaishali Nagar, Jaipur',
    fatherName: 'Vinod Gupta',
    emergencyContact: '+91 98765 11066',
    idProofType: 'Aadhaar Card',
    idProofNumber: '9901-2311-7782',
    admissionDate: '2025-04-24',
    membershipPlan: '3 Months Pro',
    membershipStatus: 'Active',
    expiryDate: '2025-07-24',
    seatNumber: 'B12',
    roomId: 'room-2',
    balanceDue: 0,
  },
  {
    id: 'stu-6',
    studentId: 'STU-1029',
    associationId: 'assoc-1',
    name: 'Meena Sharma',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    mobile: '+91 98765 11006',
    email: 'meena.s@outlook.com',
    gender: 'Female',
    dob: '2000-09-09',
    address: 'Near Civil Lines, Jaipur',
    fatherName: 'Mohan Sharma',
    emergencyContact: '+91 98765 11055',
    idProofType: 'Aadhaar Card',
    idProofNumber: '1234-5678-9012',
    admissionDate: '2024-11-06',
    membershipPlan: '6 Months Premium',
    membershipStatus: 'Expiring',
    expiryDate: '2025-05-06',
    seatNumber: 'A08',
    roomId: 'room-1',
    balanceDue: 500,
  },
  {
    id: 'stu-7',
    studentId: 'STU-1030',
    associationId: 'assoc-1',
    name: 'Vikash Kumar',
    photo: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    mobile: '+91 98765 11007',
    email: 'vikash.k@gmail.com',
    gender: 'Male',
    dob: '2001-03-25',
    address: 'D-80, Jhotwara, Jaipur',
    fatherName: 'Dinesh Kumar',
    emergencyContact: '+91 98765 11044',
    idProofType: 'Aadhaar Card',
    idProofNumber: '8877-6655-4433',
    admissionDate: '2025-02-12',
    membershipPlan: '3 Months Pro',
    membershipStatus: 'Expiring',
    expiryDate: '2025-05-12',
    seatNumber: 'B18',
    roomId: 'room-2',
    balanceDue: 0,
  },
  {
    id: 'stu-8',
    studentId: 'STU-1031',
    associationId: 'assoc-1',
    name: 'Anjali Singh',
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    mobile: '+91 98765 11008',
    email: 'anjali.singh.law@gmail.com',
    gender: 'Female',
    dob: '1999-07-30',
    address: 'Sector 5, Vidhyadhar Nagar, Jaipur',
    fatherName: 'Pratap Singh',
    emergencyContact: '+91 98765 11033',
    idProofType: 'Passport',
    idProofNumber: 'Z8901234',
    admissionDate: '2024-05-20',
    membershipPlan: '1 Year Lifetime Aspirant',
    membershipStatus: 'Expiring',
    expiryDate: '2025-05-20',
    seatNumber: 'C09',
    roomId: 'room-3',
    balanceDue: 0,
  },
  {
    id: 'stu-9',
    studentId: 'STU-1032',
    associationId: 'assoc-1',
    name: 'Rohit Yadav',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    mobile: '+91 98765 11009',
    email: 'rohit.yadav@gmail.com',
    gender: 'Male',
    dob: '2000-11-12',
    address: 'Near Tonk Phatak, Jaipur',
    fatherName: 'Rajendra Yadav',
    emergencyContact: '+91 98765 11022',
    idProofType: 'Aadhaar Card',
    idProofNumber: '3344-5566-7788',
    admissionDate: '2024-11-28',
    membershipPlan: '6 Months Premium',
    membershipStatus: 'Expiring',
    expiryDate: '2025-05-28',
    seatNumber: 'A31',
    roomId: 'room-1',
    balanceDue: 0,
  },
  {
    id: 'stu-10',
    studentId: 'STU-1033',
    associationId: 'assoc-1',
    name: 'Priya Desai',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    mobile: '+91 98765 11010',
    email: 'priya.desai@gmail.com',
    gender: 'Female',
    dob: '2002-05-02',
    address: 'C-Scheme, Ashok Nagar, Jaipur',
    fatherName: 'Naveen Desai',
    emergencyContact: '+91 98765 11011',
    idProofType: 'Aadhaar Card',
    idProofNumber: '5566-7788-9900',
    admissionDate: '2025-03-02',
    membershipPlan: '3 Months Pro',
    membershipStatus: 'Active',
    expiryDate: '2025-06-02',
    seatNumber: 'B25',
    roomId: 'room-2',
    balanceDue: 0,
  }
];

export const initialAdmissions: Admission[] = [
  {
    id: 'adm-1',
    admissionNo: 'ADM-2025-015',
    associationId: 'assoc-1',
    studentId: 'STU-1024',
    studentName: 'Pooja Sharma',
    seatNumber: 'A12',
    roomName: 'Room A - Main Reading Hall',
    planName: '6 Months Premium',
    date: '28 Apr 2025',
    amount: 5000,
    discount: 500,
    paymentMethod: 'UPI',
    status: 'Active',
    receiptNo: 'REC-78456',
  },
  {
    id: 'adm-2',
    admissionNo: 'ADM-2025-014',
    associationId: 'assoc-1',
    studentId: 'STU-1025',
    studentName: 'Amit Verma',
    seatNumber: 'B07',
    roomName: 'Room B - AC Silent Zone',
    planName: '3 Months Pro',
    date: '27 Apr 2025',
    amount: 2700,
    discount: 200,
    paymentMethod: 'Cash',
    status: 'Active',
    receiptNo: 'REC-78455',
  },
  {
    id: 'adm-3',
    admissionNo: 'ADM-2025-013',
    associationId: 'assoc-1',
    studentId: 'STU-1026',
    studentName: 'Sneha Patel',
    seatNumber: 'C15',
    roomName: 'Room C - UPSC Wing',
    planName: '1 Year Lifetime Aspirant',
    date: '26 Apr 2025',
    amount: 9000,
    discount: 1000,
    paymentMethod: 'Card',
    status: 'Active',
    receiptNo: 'REC-78454',
  },
  {
    id: 'adm-4',
    admissionNo: 'ADM-2025-012',
    associationId: 'assoc-1',
    studentId: 'STU-1027',
    studentName: 'Rohit Singh',
    seatNumber: 'A23',
    roomName: 'Room A - Main Reading Hall',
    planName: '6 Months Premium',
    date: '25 Apr 2025',
    amount: 5000,
    discount: 500,
    paymentMethod: 'UPI',
    status: 'Active',
    receiptNo: 'REC-78453',
  },
  {
    id: 'adm-5',
    admissionNo: 'ADM-2025-011',
    associationId: 'assoc-1',
    studentId: 'STU-1028',
    studentName: 'Neha Gupta',
    seatNumber: 'B12',
    roomName: 'Room B - AC Silent Zone',
    planName: '3 Months Pro',
    date: '24 Apr 2025',
    amount: 2700,
    discount: 200,
    paymentMethod: 'Cash',
    status: 'Active',
    receiptNo: 'REC-78452',
  },
];

export const initialPayments: PaymentTransaction[] = [
  {
    id: 'pay-1',
    receiptNo: 'REC-78456',
    associationId: 'assoc-1',
    studentId: 'STU-1024',
    studentName: 'Amit Kumar',
    seatNumber: 'A12',
    planName: '3 Months Pro',
    amount: 2500,
    method: 'UPI',
    date: '28 Apr 2025',
    status: 'Completed',
    notes: 'Advance renewal fee',
    deviceId: 'Reception PC',
    receivedBy: 'Rahul Sharma',
  },
  {
    id: 'pay-2',
    receiptNo: 'REC-78455',
    associationId: 'assoc-1',
    studentId: 'STU-1024',
    studentName: 'Pooja Sharma',
    seatNumber: 'A12',
    planName: '6 Months Premium',
    amount: 1500,
    method: 'Cash',
    date: '27 Apr 2025',
    status: 'Completed',
    notes: 'Admission first installment',
    deviceId: 'Reception PC',
    receivedBy: 'Pooja Verma',
  },
  {
    id: 'pay-3',
    receiptNo: 'REC-78454',
    associationId: 'assoc-1',
    studentId: 'STU-1027',
    studentName: 'Rohit Singh',
    seatNumber: 'A23',
    planName: '6 Months Premium',
    amount: 3000,
    method: 'Card',
    date: '26 Apr 2025',
    status: 'Completed',
    notes: 'Seat reservation fee',
    deviceId: 'Manager PC',
    receivedBy: 'Rahul Sharma',
  },
  {
    id: 'pay-4',
    receiptNo: 'REC-78453',
    associationId: 'assoc-1',
    studentId: 'STU-1026',
    studentName: 'Sneha Patel',
    seatNumber: 'C15',
    planName: '1 Year Lifetime',
    amount: 2000,
    method: 'UPI',
    date: '25 Apr 2025',
    status: 'Completed',
    notes: 'Locker deposit + monthly fee',
    deviceId: 'Reception PC',
    receivedBy: 'Amit Joshi',
  },
  {
    id: 'pay-5',
    receiptNo: 'REC-78452',
    associationId: 'assoc-1',
    studentId: 'STU-1028',
    studentName: 'Neha Gupta',
    seatNumber: 'B12',
    planName: '3 Months Pro',
    amount: 1500,
    method: 'Cash',
    date: '24 Apr 2025',
    status: 'Completed',
    notes: 'Partial payment',
    deviceId: 'Reception PC',
    receivedBy: 'Rahul Sharma',
  },
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  {
    id: 'att-1',
    associationId: 'assoc-1',
    studentId: 'STU-1024',
    studentName: 'Amit Kumar',
    seatNumber: 'A12',
    roomName: 'Room A - Reading Hall',
    date: '2025-04-28',
    checkIn: '10:15 AM',
    checkOut: undefined,
    durationMinutes: 0,
    status: 'Present',
  },
  {
    id: 'att-2',
    associationId: 'assoc-1',
    studentId: 'STU-1025',
    studentName: 'Pooja Sharma',
    seatNumber: 'A14',
    roomName: 'Room A - Reading Hall',
    date: '2025-04-28',
    checkIn: '08:30 AM',
    checkOut: '01:30 PM',
    durationMinutes: 300,
    status: 'Present',
  },
  {
    id: 'att-3',
    associationId: 'assoc-1',
    studentId: 'STU-1026',
    studentName: 'Rohit Singh',
    seatNumber: 'A23',
    roomName: 'Room A - Reading Hall',
    date: '2025-04-28',
    checkIn: '09:45 AM',
    checkOut: undefined,
    durationMinutes: 0,
    status: 'Late',
  },
  {
    id: 'att-4',
    associationId: 'assoc-1',
    studentId: 'STU-1027',
    studentName: 'Sneha Patel',
    seatNumber: 'C15',
    roomName: 'Room C - UPSC Wing',
    date: '2025-04-28',
    checkIn: '07:15 AM',
    checkOut: undefined,
    durationMinutes: 0,
    status: 'Present',
  },
  {
    id: 'att-5',
    associationId: 'assoc-1',
    studentId: 'STU-1028',
    studentName: 'Neha Gupta',
    seatNumber: 'B12',
    roomName: 'Room B - AC Silent Zone',
    date: '2025-04-28',
    checkIn: '09:00 AM',
    checkOut: undefined,
    durationMinutes: 0,
    status: 'Present',
  },
];

export const initialLockers: Locker[] = Array.from({ length: 40 }, (_, idx) => {
  const num = idx + 1;
  const lockerNo = `L${num < 10 ? '00' : num < 100 ? '0' : ''}${num}`;
  const isOccupied = idx % 2 === 1;
  return {
    id: `lkr-${num}`,
    associationId: 'assoc-1',
    lockerNo,
    status: isOccupied ? 'OCCUPIED' : idx === 4 ? 'MAINTENANCE' : idx === 12 ? 'RESERVED' : 'AVAILABLE',
    studentId: isOccupied ? `STU-${1024 + (idx % 8)}` : undefined,
    studentName: isOccupied ? ['Pooja Sharma', 'Amit Verma', 'Sneha Patel', 'Rohit Singh'][idx % 4] : undefined,
    deposit: isOccupied ? 500 : 0,
    expiryDate: isOccupied ? '2025-10-28' : undefined,
  };
});

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    associationId: 'assoc-1',
    title: 'Membership Expiring',
    description: '12 students membership will expire in next 7 days.',
    type: 'membership',
    timestamp: '10:20 AM',
    read: false,
    timeAgo: '12m ago',
  },
  {
    id: 'notif-2',
    associationId: 'assoc-1',
    title: 'New Admission',
    description: 'Rahul Verma has been admitted to Room A (Seat A12).',
    type: 'admission',
    timestamp: '09:45 AM',
    read: false,
    timeAgo: '47m ago',
  },
  {
    id: 'notif-3',
    associationId: 'assoc-1',
    title: 'Payment Received',
    description: '₹ 2,500 received from Sneha Patel via UPI.',
    type: 'payment',
    timestamp: '09:30 AM',
    read: false,
    timeAgo: '1h ago',
  },
  {
    id: 'notif-4',
    associationId: 'assoc-1',
    title: 'Low Seat Availability',
    description: 'Room 3 - Only 2 seats available in morning shift.',
    type: 'seats',
    timestamp: '08:15 AM',
    read: false,
    timeAgo: '2h ago',
  },
  {
    id: 'notif-5',
    associationId: 'assoc-1',
    title: 'Sync Completed',
    description: 'All local SQLite changes synchronized successfully with Supabase cloud.',
    type: 'sync',
    timestamp: '07:50 AM',
    read: true,
    timeAgo: '3h ago',
  },
];

export const initialActivities = [
  { time: '10:15 AM', type: 'checkin', title: 'Student Check-in (STU-1024)', desc: 'Amit Kumar — Seat A12', color: 'emerald' },
  { time: '09:50 AM', type: 'admission', title: 'New Admission (ADM-2025-015)', desc: 'Pooja Sharma — 6 Months Plan', color: 'blue' },
  { time: '09:30 AM', type: 'payment', title: 'Payment Received (TXN-78456)', desc: '₹ 1,500 — Cash Receipt Generated', color: 'amber' },
  { time: '09:10 AM', type: 'transfer', title: 'Seat Transfer (TRF-003)', desc: 'Rohit Singh — Transferred A23 to B12', color: 'teal' },
  { time: '08:45 AM', type: 'visitor', title: 'Visitor Check-in', desc: 'Mr. Suresh — Meeting with Administrator', color: 'purple' },
];

export const initialDevices: DeviceInfo[] = [
  { id: 'dev-1', associationId: 'assoc-1', deviceName: 'Reception PC (This Machine)', user: 'Rahul Sharma', lastActive: 'Just Now', lastSync: '10:24 AM', status: 'Online', ip: '192.168.1.101' },
  { id: 'dev-2', associationId: 'assoc-1', deviceName: 'Manager PC', user: 'Pooja Verma', lastActive: '4 mins ago', lastSync: '10:20 AM', status: 'Online', ip: '192.168.1.102' },
  { id: 'dev-3', associationId: 'assoc-1', deviceName: 'Owner Laptop', user: 'Director Office', lastActive: '45 mins ago', lastSync: '09:50 AM', status: 'Offline', ip: '192.168.1.105' },
];

export const initialStaff: StaffMember[] = [
  { id: 'stf-1', associationId: 'assoc-1', name: 'Rahul Sharma', role: 'Super Admin', mobile: '+91 98765 43210', email: 'rahul@lib.com', salary: 65000, shift: 'Full Day (8 AM - 8 PM)', status: 'Active', joiningDate: '2022-01-15' },
  { id: 'stf-2', associationId: 'assoc-1', name: 'Pooja Verma', role: 'Manager', mobile: '+91 98765 43211', email: 'pooja@lib.com', salary: 38000, shift: 'Morning (6 AM - 2 PM)', status: 'Active', joiningDate: '2023-04-10' },
  { id: 'stf-3', associationId: 'assoc-1', name: 'Amit Joshi', role: 'Receptionist', mobile: '+91 98765 43212', email: 'amit@lib.com', salary: 22000, shift: 'Evening (2 PM - 10 PM)', status: 'Active', joiningDate: '2024-02-01' },
  { id: 'stf-4', associationId: 'assoc-1', name: 'Rajendra Meena', role: 'Security', mobile: '+91 98765 43213', email: 'security@lib.com', salary: 16000, shift: 'Full Day (8 AM - 8 PM)', status: 'Active', joiningDate: '2023-08-15' },
  { id: 'stf-5', associationId: 'assoc-1', name: 'Sunita Devi', role: 'Librarian', mobile: '+91 98765 43214', email: 'sunita@lib.com', salary: 25000, shift: 'Morning (6 AM - 2 PM)', status: 'Active', joiningDate: '2023-11-20' },
];

export const initialExpenses: Expense[] = [
  { id: 'exp-1', associationId: 'assoc-1', category: 'Electricity', amount: 34500, date: '2025-04-20', vendor: 'Jaipur Vidyut Vitran Nigam Ltd', method: 'Bank Transfer', description: 'Commercial reading hall meter electricity bill for March-April' },
  { id: 'exp-2', associationId: 'assoc-1', category: 'Internet', amount: 6800, date: '2025-04-15', vendor: 'Airtel Enterprise Fiber (1 Gbps)', method: 'UPI', description: 'Dual line redundant high-speed broadband monthly lease' },
  { id: 'exp-3', associationId: 'assoc-1', category: 'Maintenance', amount: 4200, date: '2025-04-18', vendor: 'Daikin AC Service Partner', method: 'Cash', description: 'Deep filter cleaning and compressor check for Room A ACs' },
  { id: 'exp-4', associationId: 'assoc-1', category: 'Supplies', amount: 2800, date: '2025-04-22', vendor: 'Modern Stationers', method: 'UPI', description: 'Thermal printer rolls (80mm x 50 rolls) and A4 printing paper' },
  { id: 'exp-5', associationId: 'assoc-1', category: 'Cleaning', amount: 3500, date: '2025-04-25', vendor: 'CleanPro Facility Solutions', method: 'Cash', description: 'Sanitization chemicals, desk polish and cleaning supplies' },
];

export const initialNotices: Notice[] = [
  { id: 'not-1', associationId: 'assoc-1', title: 'Extended 24/7 Hours for UPSC Prelims Aspirants', content: 'Starting May 1st, Room A and Room C will be operating 24 hours non-stop with night security for registered aspirants.', category: 'Announcement', audience: 'All Students', date: '28 Apr 2025', status: 'Active', pinned: true },
  { id: 'not-2', associationId: 'assoc-1', title: 'High-Speed Wi-Fi Router Maintenance on Sunday', content: 'Broadband routers in Room B will undergo scheduled firmware upgrade on Sunday 6:00 AM - 7:00 AM.', category: 'Maintenance', audience: 'All Students', date: '26 Apr 2025', status: 'Active', pinned: false },
  { id: 'not-3', associationId: 'assoc-1', title: 'Strict Silence Policy in AC Silent Zone', content: 'Students are requested to keep phones on complete silent mode. Phone calls must be attended outside in lobby only.', category: 'Rules', audience: 'All Students', date: '22 Apr 2025', status: 'Active', pinned: false },
];

export const initialVisitors: Visitor[] = [
  { id: 'vis-1', associationId: 'assoc-1', name: 'Suresh Kumar', mobile: '+91 98290 44551', purpose: 'Inquiry for 1 Year Admission', visitedPerson: 'Rahul Sharma (Admin)', entryTime: '08:45 AM', exitTime: '09:15 AM', date: '28 Apr 2025', status: 'Exited' },
  { id: 'vis-2', associationId: 'assoc-1', name: 'Deepak Sharma', mobile: '+91 94140 33221', purpose: 'Guardian visit for student STU-1024', visitedPerson: 'Pooja Sharma', entryTime: '10:30 AM', exitTime: undefined, date: '28 Apr 2025', status: 'Inside' },
];

export const initialComplaints: Complaint[] = [
  { id: 'cmp-1', complaintNo: 'CMP-2025-008', associationId: 'assoc-1', studentId: 'STU-1025', studentName: 'Amit Verma', category: 'Air Conditioning', description: 'AC unit #2 in Room B blowing warm air near seat B07.', priority: 'High', assignedStaff: 'Pooja Verma', status: 'In Progress', date: '28 Apr 2025' },
  { id: 'cmp-2', complaintNo: 'CMP-2025-007', associationId: 'assoc-1', studentId: 'STU-1027', studentName: 'Rohit Singh', category: 'Lighting', description: 'Study lamp flicker on desk A23.', priority: 'Medium', assignedStaff: 'Amit Joshi', status: 'Resolved', date: '27 Apr 2025', resolution: 'Bulb fixture replaced with new 9W warm LED.' },
];

export const initialAuditLogs: AuditLog[] = [
  { id: 'aud-1', associationId: 'assoc-1', userId: 'usr-1', userName: 'Rahul Sharma', device: 'Reception PC', action: 'STUDENT_ADMISSION', module: 'Admissions', details: 'Admitted Pooja Sharma (STU-1024) to Seat A12 for 6 Months Premium plan.', timestamp: '2025-04-28 09:50:12' },
  { id: 'aud-2', associationId: 'assoc-1', userId: 'usr-1', userName: 'Rahul Sharma', device: 'Reception PC', action: 'PAYMENT_COLLECTED', module: 'Payments', details: 'Recorded payment ₹1,500 cash from Pooja Sharma (REC-78456).', timestamp: '2025-04-28 09:52:45' },
  { id: 'aud-3', associationId: 'assoc-1', userId: 'usr-1', userName: 'Rahul Sharma', device: 'Reception PC', action: 'SEAT_TRANSFER', module: 'Seats', details: 'Transferred Rohit Singh from Seat A23 to B12 upon student request.', timestamp: '2025-04-28 09:10:04' },
];
